### ISSUE TITLE
[Android] 카카오 앱 미설치 시 앱 오류

### ISSUE THREAD

**Issue by hyeseon-han** [millo-L/react-native-kakao-share-link#12]
카카오 앱이 설치 되어있지 않은 경우 앱 크래시가 나는데 오류를 보니 KakaoCustomTabsClient에 문제가 있는 것 같습니다. 

> android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ContextImpl.startActivity(ContextImpl.java:974)
        at android.app.ContextImpl.startActivity(ContextImpl.java:950)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:384)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:384)
        at com.kakao.sdk.common.util.KakaoCustomTabsClient$openWithDefault$connection$1.onCustomTabsServiceConnected(KakaoCustomTabsClient.kt:48)
        at androidx.browser.customtabs.CustomTabsServiceConnection.onServiceConnected(CustomTabsServiceConnection.java:57)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1839)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1871)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by qnrjs42** [comment]
안드로이드에서 같은 문제를 겪고 있습니다.

react-native: 0.69
react-native-kakao-share-link: 1.0.6
kakao sdk: 2.9.1
